apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-manual-testing-existing-default-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/chatbot-manual-testing-existing-default:004d3fb0ce84c7480546a62fd5fd39a6df11a842@sha256:f22a9eccddba140d0f3f50ccfbbe69f2ce648939f017d01062477a32623bc2f0 # use pre-built to bootstrap 
          name: app-inference
