---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: chatbot-manual-testing-existing-default-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: chatbot-manual-testing-existing-default-1 
  name: chatbot-manual-testing-existing-default-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi